# https://www.webstoemp.com/blog/github-actions-deploy-craftcms/
# https://swharden.com/blog/2022-04-24-github-actions-ftp/

name: ðŸš€ Craft Deploy
on:
  push:
    branches:
      - main 
  workflow_dispatch:
  
env:
  APP_PATH: ~/craft/kortkijk
  WEB_PATH: ~/www/kortkijk
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v3

      # Setup container with private SSH Key (used by rsync)
      - name: Load private SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # RSYNC
      # - rsync [options] ~/localdir ssh_user@ssh_host:destination_directory
      # - exclude web/uploads is there to avoid deleting user uploaded files w/ --delete-after
      # - StrictHostKeyChecking=no will automatically add new host keys to the user known hosts files.
      - name: Deploy craft project with rsync
        run: |
          rsync -azh --delete-after --exclude={"/.env","/.ddev/","/web/","/node_modules/","/.git/","/.github/"} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{env.APP_PATH}}

      - name: Deploy web files with rsync
        run: |
          rsync -azh --delete-after --exclude 'index.php' -e "ssh -o StrictHostKeyChecking=no" ./web/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{env.WEB_PATH}}


      # execute commands on remote server
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.APP_PATH }}
            mkdir -p storage
            composer install --no-interaction --no-progress --no-suggest --optimize-autoloader
            chmod a+x craft
            php craft db/backup
            php craft update/composer-install --interactive=0
            php craft migrate/all --no-content --interactive=0
            php craft project-config/apply
            php craft migrate --track=content --interactive=0
            php craft clear-caches/all
            npm install
            npm run build
            mv web/dist ${{env.WEB_PATH}}
